### ISSUE TITLE
C Compiler?

### ISSUE THREAD

**Issue by rdb9879** [mballance/fwrisc#1]
I am trying to write a simple test program written in C to target your fwrisc processor. The goal is to jump into a single function/subroutine, write to an LED register address, return from the function, and go into an idle-forever-loop. I'm compiling the C code and then loading into block RAM

My analysis of watching the program counter is that the branches and jal commands are jumping 4 bytes too far, as well as the address loaded into the ra register. 

At this point, I just want to verify that I have the correct C compiler with the correct settings. Could you share this information?

Here is what I have installed, from the riscv-gnu-toolchain:

riscv32-unknown-elf-gcc -v
Using built-in specs.
COLLECT_GCC=riscv32-unknown-elf-gcc
COLLECT_LTO_WRAPPER=/opt/riscv/libexec/gcc/riscv32-unknown-elf/9.2.0/lto-wrapper
Target: riscv32-unknown-elf
Configured with: /home/ghdl/riscv/compiler/riscv-gnu-toolchain/riscv-gcc/configure --target=riscv32-unknown-elf --prefix=/opt/riscv --disable-shared --disable-threads --enable-languages=c,c++ --with-system-zlib --enable-tls --with-newlib --with-sysroot=/opt/riscv/riscv32-unknown-elf --with-native-system-header-dir=/include --disable-libmudflap --disable-libssp --disable-libquadmath --disable-libgomp --disable-nls --disable-tm-clone-registry --src=.././riscv-gcc --enable-checking=yes --disable-multilib --with-abi=ilp32 --with-arch=rv32i --with-tune=rocket 'CFLAGS_FOR_TARGET=-Os  -mcmodel=medlow' 'CXXFLAGS_FOR_TARGET=-Os  -mcmodel=medlow'
Thread model: single
gcc version 9.2.0 (GCC)

**Comment by mballance** [comment]
Hello,
    Hmm... That's interesting... I've used two GCC toolchains -- one that I
built myself, and one that is provided for use with the Zephyr OS. Here are
the specs for the GCC I built myself:

 [ballance@localhost unit]$ riscv32-unknown-elf-gcc -v
Using built-in specs.
COLLECT_GCC=riscv32-unknown-elf-gcc
COLLECT_LTO_WRAPPER=/project/tools/compilers/gcc-riscv32-elf-7.3.0-linux_x86_64/bin/../libexec/gcc/riscv32-unknown-elf/7.3.0/lto-wrapper
Target: riscv32-unknown-elf
Configured with: ../../gcc-riscv-elf/gcc-7.3.0/configure
--target=riscv32-unknown-elf
--prefix=/project/fun/cross-tool-scripts/cross-tools-scripts/build/gcc-riscv32-elf/installdir
--enable-languages=c,c++ --disable-shared --disable-libssp --with-newlib
Thread model: single
gcc version 7.3.0 (GCC)

    I am passing -march=rv32i -mabi=ilp32 to the compiler. Are you doing
this as well?

Thanks,
Matthew

**Comment by rdb9879** [comment]
I am indeed using -march=rv32i and -mabi=ilp32

**Comment by mballance** [comment]
Just wanted to confirm your original problem report. You report that jump targets are 4 bytes beyond the expected target, and that the address in the ra register is also 4 beyond. The expected branch/jump target os (pc+offset) and the expected ra value after a jal is (pc+4). Based on your report, you are observing a branch/jump destination address of (pc+offset+4) and an ra value of (pc+8). Is this correct?

**Comment by rdb9879** [comment]
That is correct.

**Comment by mballance** [comment]
Hmm.... We're certainly seeing different things! Here is the disassembly and execution trace from the fwrisc_instr_tests_jump_jal test:

# Disassembly
80000000 <_start>:
80000000:	0080006f          	j	80000008 <entry>

80000004 <done>:
80000004:	0000006f          	j	80000004 <done>

80000008 <entry>:
80000008:	00c000ef          	jal	ra,80000014 <entry+0xc>
8000000c:	0001a137          	lui	sp,0x1a
80000010:	0001a137          	lui	sp,0x1a
80000014:	00000197          	auipc	gp,0x0
80000018:	ff418193          	addi	gp,gp,-12 # 80000008 <entry>
8000001c:	40308233          	sub	tp,ra,gp
80000020:	00000093          	li	ra,0
80000024:	00000193          	li	gp,0
80000028:	fddff06f          	j	80000004 <done>


# Execution Trace
exec: 0x80000000 - 0x0080006f
regwrite: 0x01 <= 0x8000000c
exec: 0x80000008 - 0x00c000ef
regwrite: 0x03 <= 0x80000014
exec: 0x80000014 - 0x00000197
regwrite: 0x03 <= 0x80000008
exec: 0x80000018 - 0xff418193
regwrite: 0x04 <= 0x00000004
exec: 0x8000001c - 0x40308233
regwrite: 0x01 <= 0x00000000
exec: 0x80000020 - 0x00000093
regwrite: 0x03 <= 0x00000000
exec: 0x80000024 - 0x00000193
exec: 0x80000028 - 0xfddff06f
exec: 0x80000004 - 0x0000006f

The jump target address is calculated correctly according to the disassembly, and I can see the link register being written with PC+4 (instruction 0x80000008). Is there a testcase you can share that shows the incorrect behavior?

Thanks,
Matthew
